// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for InvoiceApprovalStatus.
const (
	Approved        InvoiceApprovalStatus = "Approved"
	Draft           InvoiceApprovalStatus = "Draft"
	PendingApproval InvoiceApprovalStatus = "Pending Approval"
	Posted          InvoiceApprovalStatus = "Posted"
	Returned        InvoiceApprovalStatus = "Returned"
)

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	ApprovalStatus   *InvoiceApprovalStatus `json:"approval_status,omitempty"`
	CreatedAt        *time.Time             `json:"created_at,omitempty"`
	CurrencyCode     string                 `json:"currency_code"`
	CustomerId       openapi_types.UUID     `json:"customer_id"`
	GrandTotalAmount *float64               `json:"grand_total_amount,omitempty"`
	Id               *openapi_types.UUID    `json:"id,omitempty"`
	InvoiceDate      openapi_types.Date     `json:"invoice_date"`
	InvoiceNo        string                 `json:"invoice_no"`
	InvoiceType      *string                `json:"invoice_type,omitempty"`
	JobId            *openapi_types.UUID    `json:"job_id,omitempty"`
}

// InvoiceApprovalStatus defines model for Invoice.ApprovalStatus.
type InvoiceApprovalStatus string

// Receipt defines model for Receipt.
type Receipt struct {
	ApprovalStatus         *string             `json:"approval_status,omitempty"`
	CurrencyCode           string              `json:"currency_code"`
	CustomerId             openapi_types.UUID  `json:"customer_id"`
	Id                     *openapi_types.UUID `json:"id,omitempty"`
	ReceiptDate            openapi_types.Date  `json:"receipt_date"`
	ReceiptNo              string              `json:"receipt_no"`
	ReceivedAmountCustomer *float64            `json:"received_amount_customer,omitempty"`
}

// TenantID defines model for TenantID.
type TenantID = openapi_types.UUID

// ListInvoicesParams defines parameters for ListInvoices.
type ListInvoicesParams struct {
	CustomerId *openapi_types.UUID `form:"customer_id,omitempty" json:"customer_id,omitempty"`
	Status     *string             `form:"status,omitempty" json:"status,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                `form:"offset,omitempty" json:"offset,omitempty"`

	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateInvoiceParams defines parameters for CreateInvoice.
type CreateInvoiceParams struct {
	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// GetInvoiceParams defines parameters for GetInvoice.
type GetInvoiceParams struct {
	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// ListReceiptsParams defines parameters for ListReceipts.
type ListReceiptsParams struct {
	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateReceiptParams defines parameters for CreateReceipt.
type CreateReceiptParams struct {
	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// ProvisionTenantJSONBody defines parameters for ProvisionTenant.
type ProvisionTenantJSONBody struct {
	SchemaName *string `json:"schema_name,omitempty"`
}

// ProvisionTenantParams defines parameters for ProvisionTenant.
type ProvisionTenantParams struct {
	// XTenantID Tenant identifier
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateInvoiceJSONRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody = Invoice

// CreateReceiptJSONRequestBody defines body for CreateReceipt for application/json ContentType.
type CreateReceiptJSONRequestBody = Receipt

// ProvisionTenantJSONRequestBody defines body for ProvisionTenant for application/json ContentType.
type ProvisionTenantJSONRequestBody ProvisionTenantJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List invoices
	// (GET /invoices)
	ListInvoices(w http.ResponseWriter, r *http.Request, params ListInvoicesParams)
	// Create invoice
	// (POST /invoices)
	CreateInvoice(w http.ResponseWriter, r *http.Request, params CreateInvoiceParams)
	// Get invoice
	// (GET /invoices/{invoice_id})
	GetInvoice(w http.ResponseWriter, r *http.Request, invoiceId openapi_types.UUID, params GetInvoiceParams)
	// List receipts
	// (GET /receipts)
	ListReceipts(w http.ResponseWriter, r *http.Request, params ListReceiptsParams)
	// Create receipt
	// (POST /receipts)
	CreateReceipt(w http.ResponseWriter, r *http.Request, params CreateReceiptParams)
	// Provision finance schema for a tenant
	// (POST /tenants/provision)
	ProvisionTenant(w http.ResponseWriter, r *http.Request, params ProvisionTenantParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List invoices
// (GET /invoices)
func (_ Unimplemented) ListInvoices(w http.ResponseWriter, r *http.Request, params ListInvoicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create invoice
// (POST /invoices)
func (_ Unimplemented) CreateInvoice(w http.ResponseWriter, r *http.Request, params CreateInvoiceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get invoice
// (GET /invoices/{invoice_id})
func (_ Unimplemented) GetInvoice(w http.ResponseWriter, r *http.Request, invoiceId openapi_types.UUID, params GetInvoiceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List receipts
// (GET /receipts)
func (_ Unimplemented) ListReceipts(w http.ResponseWriter, r *http.Request, params ListReceiptsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create receipt
// (POST /receipts)
func (_ Unimplemented) CreateReceipt(w http.ResponseWriter, r *http.Request, params CreateReceiptParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Provision finance schema for a tenant
// (POST /tenants/provision)
func (_ Unimplemented) ProvisionTenant(w http.ResponseWriter, r *http.Request, params ProvisionTenantParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListInvoices operation middleware
func (siw *ServerInterfaceWrapper) ListInvoices(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInvoicesParams

	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", r.URL.Query(), &params.CustomerId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customer_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvoices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateInvoice operation middleware
func (siw *ServerInterfaceWrapper) CreateInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateInvoiceParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvoice(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetInvoice operation middleware
func (siw *ServerInterfaceWrapper) GetInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "invoice_id" -------------
	var invoiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "invoice_id", runtime.ParamLocationPath, chi.URLParam(r, "invoice_id"), &invoiceId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoice_id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInvoiceParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvoice(w, r, invoiceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListReceipts operation middleware
func (siw *ServerInterfaceWrapper) ListReceipts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReceiptsParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReceipts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateReceipt operation middleware
func (siw *ServerInterfaceWrapper) CreateReceipt(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateReceiptParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateReceipt(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ProvisionTenant operation middleware
func (siw *ServerInterfaceWrapper) ProvisionTenant(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ProvisionTenantParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Tenant-ID", runtime.ParamLocationHeader, valueList[0], &XTenantID)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProvisionTenant(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/invoices", wrapper.ListInvoices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/invoices", wrapper.CreateInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/invoices/{invoice_id}", wrapper.GetInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/receipts", wrapper.ListReceipts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/receipts", wrapper.CreateReceipt)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tenants/provision", wrapper.ProvisionTenant)
	})

	return r
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200TextResponse string

func (response HealthCheck200TextResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type ListInvoicesRequestObject struct {
	Params ListInvoicesParams
}

type ListInvoicesResponseObject interface {
	VisitListInvoicesResponse(w http.ResponseWriter) error
}

type ListInvoices200JSONResponse struct {
	Invoices *[]Invoice `json:"invoices,omitempty"`
	Total    *int       `json:"total,omitempty"`
}

func (response ListInvoices200JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInvoices401Response struct {
}

func (response ListInvoices401Response) VisitListInvoicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListInvoices403Response struct {
}

func (response ListInvoices403Response) VisitListInvoicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type CreateInvoiceRequestObject struct {
	Params CreateInvoiceParams
	Body   *CreateInvoiceJSONRequestBody
}

type CreateInvoiceResponseObject interface {
	VisitCreateInvoiceResponse(w http.ResponseWriter) error
}

type CreateInvoice201JSONResponse Invoice

func (response CreateInvoice201JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvoice400JSONResponse Error

func (response CreateInvoice400JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetInvoiceRequestObject struct {
	InvoiceId openapi_types.UUID `json:"invoice_id"`
	Params    GetInvoiceParams
}

type GetInvoiceResponseObject interface {
	VisitGetInvoiceResponse(w http.ResponseWriter) error
}

type GetInvoice200JSONResponse Invoice

func (response GetInvoice200JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInvoice404Response struct {
}

func (response GetInvoice404Response) VisitGetInvoiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListReceiptsRequestObject struct {
	Params ListReceiptsParams
}

type ListReceiptsResponseObject interface {
	VisitListReceiptsResponse(w http.ResponseWriter) error
}

type ListReceipts200JSONResponse struct {
	Receipts *[]Receipt `json:"receipts,omitempty"`
}

func (response ListReceipts200JSONResponse) VisitListReceiptsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateReceiptRequestObject struct {
	Params CreateReceiptParams
	Body   *CreateReceiptJSONRequestBody
}

type CreateReceiptResponseObject interface {
	VisitCreateReceiptResponse(w http.ResponseWriter) error
}

type CreateReceipt201JSONResponse Receipt

func (response CreateReceipt201JSONResponse) VisitCreateReceiptResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ProvisionTenantRequestObject struct {
	Params ProvisionTenantParams
	Body   *ProvisionTenantJSONRequestBody
}

type ProvisionTenantResponseObject interface {
	VisitProvisionTenantResponse(w http.ResponseWriter) error
}

type ProvisionTenant200Response struct {
}

func (response ProvisionTenant200Response) VisitProvisionTenantResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ProvisionTenant400Response struct {
}

func (response ProvisionTenant400Response) VisitProvisionTenantResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ProvisionTenant500Response struct {
}

func (response ProvisionTenant500Response) VisitProvisionTenantResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// List invoices
	// (GET /invoices)
	ListInvoices(ctx context.Context, request ListInvoicesRequestObject) (ListInvoicesResponseObject, error)
	// Create invoice
	// (POST /invoices)
	CreateInvoice(ctx context.Context, request CreateInvoiceRequestObject) (CreateInvoiceResponseObject, error)
	// Get invoice
	// (GET /invoices/{invoice_id})
	GetInvoice(ctx context.Context, request GetInvoiceRequestObject) (GetInvoiceResponseObject, error)
	// List receipts
	// (GET /receipts)
	ListReceipts(ctx context.Context, request ListReceiptsRequestObject) (ListReceiptsResponseObject, error)
	// Create receipt
	// (POST /receipts)
	CreateReceipt(ctx context.Context, request CreateReceiptRequestObject) (CreateReceiptResponseObject, error)
	// Provision finance schema for a tenant
	// (POST /tenants/provision)
	ProvisionTenant(ctx context.Context, request ProvisionTenantRequestObject) (ProvisionTenantResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHttpHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHttpMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInvoices operation middleware
func (sh *strictHandler) ListInvoices(w http.ResponseWriter, r *http.Request, params ListInvoicesParams) {
	var request ListInvoicesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvoices(ctx, request.(ListInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvoices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInvoicesResponseObject); ok {
		if err := validResponse.VisitListInvoicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInvoice operation middleware
func (sh *strictHandler) CreateInvoice(w http.ResponseWriter, r *http.Request, params CreateInvoiceParams) {
	var request CreateInvoiceRequestObject

	request.Params = params

	var body CreateInvoiceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvoice(ctx, request.(CreateInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvoice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInvoiceResponseObject); ok {
		if err := validResponse.VisitCreateInvoiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInvoice operation middleware
func (sh *strictHandler) GetInvoice(w http.ResponseWriter, r *http.Request, invoiceId openapi_types.UUID, params GetInvoiceParams) {
	var request GetInvoiceRequestObject

	request.InvoiceId = invoiceId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInvoice(ctx, request.(GetInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInvoice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInvoiceResponseObject); ok {
		if err := validResponse.VisitGetInvoiceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReceipts operation middleware
func (sh *strictHandler) ListReceipts(w http.ResponseWriter, r *http.Request, params ListReceiptsParams) {
	var request ListReceiptsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListReceipts(ctx, request.(ListReceiptsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReceipts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReceiptsResponseObject); ok {
		if err := validResponse.VisitListReceiptsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateReceipt operation middleware
func (sh *strictHandler) CreateReceipt(w http.ResponseWriter, r *http.Request, params CreateReceiptParams) {
	var request CreateReceiptRequestObject

	request.Params = params

	var body CreateReceiptJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateReceipt(ctx, request.(CreateReceiptRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateReceipt")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateReceiptResponseObject); ok {
		if err := validResponse.VisitCreateReceiptResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProvisionTenant operation middleware
func (sh *strictHandler) ProvisionTenant(w http.ResponseWriter, r *http.Request, params ProvisionTenantParams) {
	var request ProvisionTenantRequestObject

	request.Params = params

	var body ProvisionTenantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProvisionTenant(ctx, request.(ProvisionTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProvisionTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProvisionTenantResponseObject); ok {
		if err := validResponse.VisitProvisionTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
